['block',
  ['declaration',
    ['property',
      ['ident', 'p0']],
    ['propertyDelim'],
    ['value',
      ['ident', 'v0']]],
  ['declDelim'],
  ['declaration',
    ['property',
      ['ident', 'p1']],
    ['propertyDelim'],
    ['value',
      ['ident', 'v1']]]]
