['block',
  ['declaration',
    ['property',
      ['ident', 'p0']],
    ['value',
      ['ident', 'v0'],
      ['s', ' '],
      ['block',
        ['declaration',
          ['property',
            ['ident', 'a']],
          ['value',
            ['ident', 'b']]]]]],
  ['s', ' '],
  ['declaration',
    ['property',
      ['ident', 'p1']],
    ['value',
      ['ident', 'v1']]]]
