['block',
  ['commentML', 'test'],
  ['declaration',
    ['property',
      ['ident', 'p']],
    ['propertyDelim'],
    ['value',
      ['ident', 'v'],
      ['commentML', 'test']]],
  ['declDelim'],
  ['commentML', 'test']]
