['block',
  ['commentML', 'test'],
  ['declaration',
    ['property',
      ['ident', 'p0']],
    ['propertyDelim'],
    ['value',
      ['ident', 'v0'],
      ['commentML', 'test']]],
  ['decldelim'],
  ['commentML', 'test'],
  ['declaration',
    ['property',
      ['ident', 'p1']],
    ['propertyDelim'],
    ['value',
      ['ident', 'v1'],
      ['commentML', 'test']]]]
