['block',
  ['s', '  '],
  ['declaration',
    ['property',
      ['ident', 'p0']],
    ['propertyDelim'],
    ['value',
      ['ident', 'v0']]],
  ['s', '  '],
  ['declDelim'],
  ['s', '  '],
  ['declaration',
    ['property',
      ['ident', 'p1']],
    ['propertyDelim'],
    ['value',
      ['ident', 'v1']]],
  ['s', '  ']]
