['function',
  ['ident', 'f'],
  ['arguments',
    ['declaration',
      ['property',
        ['variable',
          ['ident', 'n']]],
      ['propertyDelim'],
      ['value',
        ['number', '5']]]]]
