['atrules',
  ['atkeyword',
    ['ident', 'import']],
  ['s', ' '],
  ['string', '"library.less"'],
  ['s', ' '],
  ['ident', 'screen'],
  ['s', ' '],
  ['ident', 'and'],
  ['s', ' '],
  ['braces', '(', ')',
    ['ident', 'max-width'],
    ['operator', ':'],
    ['s', ' '],
    ['dimension',
      ['number', '400'],
      ['ident', 'px']]]]