['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['class',
          ['ident', 'nani']],
        ['s', '
']]],
    ['block',
      ['s', '  '],
      ['declaration',
        ['property',
          ['ident', 'a']],
        ['propertyDelim'],
        ['value',
          ['ident', 'b']]],
      ['s', '
']]],
  ['include',
    ['atkeyword',
      ['ident', 'extend']],
    ['s', ' '],
    ['simpleselector',
      ['class',
        ['ident', 'nani']]]]]
