['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['ident', 'a'],
        ['s', '
']]],
    ['block',
      ['s', '  '],
      ['declaration',
        ['property',
          ['ident', 'color']],
        ['propertyDelim'],
        ['s', ' '],
        ['value',
          ['ident', 'tomato']]],
      ['declDelim'],
      ['s', '
'],
      ['s', '  '],
      ['ruleset',
        ['selector',
          ['simpleselector',
            ['ident', 'p'],
            ['s', '
']]],
        ['block',
          ['s', '    '],
          ['declaration',
            ['property',
              ['ident', 'top']],
            ['propertyDelim'],
            ['s', ' '],
            ['value',
              ['number', '0']]]]]]]]
