['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['ident', 'a'],
        ['s', '
']]],
    ['block',
      ['s', '  '],
      ['include',
        ['operator', '+'],
        ['simpleselector',
          ['ident', 'inline-block']]],
      ['declDelim'],
      ['s', '  '],
      ['declaration',
        ['property',
          ['ident', 'color']],
        ['propertyDelim'],
        ['s', ' '],
        ['value',
          ['ident', 'tomato']]]]]]
