['mixin',
  ['class',
    ['ident', 'nani']],
  ['s', ' '],
  ['arguments',
    ['declaration',
      ['property',
        ['variable',
          ['ident', 'color']]],
      ['value',
        ['s', ' '],
        ['ident', 'tomato']]]],
  ['s', ' '],
  ['block',
    ['declaration',
      ['property',
        ['ident', 'color']],
      ['value',
        ['variable',
          ['ident', 'color']]]]]]
