['mixin',
  ['clazz',
    ['ident', 'nani']],
  ['s', ' '],
  ['arguments',
    ['variable',
      ['ident', 'foo']],
    ['decldelim'],
    ['s', ' '],
    ['declaration',
      ['property',
        ['variable',
          ['ident', 'color']]],
      ['value',
        ['s', ' '],
        ['ident', 'tomato']]]],
  ['s', ' '],
  ['block',
    ['declaration',
      ['property',
        ['ident', 'color']],
      ['value',
        ['variable',
          ['ident', 'color']]]]]]
