['mixin',
  ['class',
    ['ident', 'nani']],
  ['s', ' '],
  ['arguments'],
  ['s', ' '],
  ['block',
    ['declaration',
      ['property',
        ['ident', 'color']],
      ['propertyDelim'],
      ['value',
        ['variable',
          ['ident', 'color']]]]]]
