['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's'],
      ['commentML', 'test']]],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['commentML', 'test'],
      ['propertyDelim'],
      ['commentML', 'test'],
      ['value',
        ['ident', 'v']]],
    ['commentML', 'test']]]
