['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's'],
      ['commentML', 'test']]],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['commentML', 'test'],
      ['propertyDelim'],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v'],
        ['commentML', 'test']]]]]
