['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's'],
      ['commentML', 'test']]],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p0'],
        ['commentML', 'test']],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v0'],
        ['commentML', 'test']]],
    ['decldelim'],
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p1'],
        ['commentML', 'test']],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v1'],
        ['commentML', 'test']]]]]
