['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's'],
      ['commentML', 'test']]],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p0']],
      ['commentML', 'test'],
      ['propertyDelim'],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v0'],
        ['commentML', 'test']]],
    ['declDelim'],
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p1']],
      ['commentML', 'test'],
      ['propertyDelim'],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v1'],
        ['commentML', 'test']]]]]
