['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's0'],
      ['commentML', 'test']],
    ['delim'],
    ['simpleselector',
      ['commentML', 'test'],
      ['ident', 's1'],
      ['commentML', 'test']]],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p0'],
        ['commentML', 'test']],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v0'],
        ['commentML', 'test']]],
    ['decldelim'],
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p1'],
        ['commentML', 'test']],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v1'],
        ['commentML', 'test']]]]]
