['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's'],
      ['s', '  ']]],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p'],
        ['s', '  ']],
      ['propertyDelim'],
      ['value',
        ['s', '  '],
        ['ident', 'v'],
        ['s', '  ']]]]]
