['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's'],
      ['s', '  ']]],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p0'],
        ['s', '  ']],
      ['propertyDelim'],
      ['value',
        ['s', '  '],
        ['ident', 'v0'],
        ['s', '  ']]],
    ['declDelim'],
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p1'],
        ['s', '  ']],
      ['propertyDelim'],
      ['value',
        ['s', '  '],
        ['ident', 'v1'],
        ['s', '  ']]]]]
