['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's0'],
      ['s', '  ']],
    ['delim'],
    ['simpleselector',
      ['s', '  '],
      ['ident', 's1'],
      ['s', '  ']]],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p'],
        ['s', '  ']],
      ['propertyDelim'],
      ['value',
        ['s', '  '],
        ['ident', 'v'],
        ['s', '  ']]]]]
