['loop',
  ['atkeyword',
    ['ident', 'while']],
  ['s', ' '],
  ['number', '1'],
  ['s', ' '],
  ['operator', '>'],
  ['s', ' '],
  ['number', '2'],
  ['s', '
'],
  ['block',
    ['s', '  '],
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['ident', 'a'],
          ['s', '
']]],
      ['block',
        ['s', '    '],
        ['declaration',
          ['property',
            ['ident', 'p']],
          ['propertyDelim'],
          ['value',
            ['ident', 'v']]]]]]]

