['loop',
  ['atkeyword',
    ['ident', 'for']],
  ['s', ' '],
  ['variable',
    ['ident', 'i']],
  ['s', ' '],
  ['ident', 'from'],
  ['s', ' '],
  ['number', '1'],
  ['s', ' '],
  ['ident', 'through'],
  ['s', ' '],
  ['number', '3'],
  ['s', '
'],
  ['block',
    ['s', '  '],
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['ident', 'a'],
          ['s', '
']]],
      ['block',
        ['s', '    '],
        ['declaration',
          ['property',
            ['ident', 'p']],
          ['propertyDelim'],
          ['value',
            ['ident', 'v']]]]]]]


