['declaration',
  ['property',
    ['ident', 'property'],
    ['s', '  '],
    ['commentML', 'test'],
    ['s', '  ']],
  ['value',
    ['s', '  '],
    ['commentML', 'test'],
    ['s', '  '],
    ['ident', 'value']]]
