['declaration',
  ['property',
    ['ident', 'property']],
  ['s', '  '],
  ['commentML', 'test'],
  ['s', '  '],
  ['propertyDelim'],
  ['value',
    ['s', '  '],
    ['commentML', 'test'],
    ['s', '  '],
    ['ident', 'value']]]
