['mixin',
  ['atkeyword',
    ['ident', 'mixin']],
  ['s', ' '],
  ['ident', 'nani'],
  ['s', ' '],
  ['block',
    ['declaration',
      ['property',
        ['ident', 'color']],
      ['propertyDelim'],
      ['value',
        ['ident', 'tomato']]]]]
