['mixin',
  ['atkeyword',
    ['ident', 'mixin']],
  ['s', ' '],
  ['ident', 'nani'],
  ['s', ' '],
  ['arguments',
    ['variable',
      ['ident', 'v1']]],
  ['s', ' '],
  ['block',
    ['declaration',
      ['property',
        ['ident', 'x']],
      ['value',
        ['ident', 'y']]]]]
