describe 'less/pseudoc >>', ->

  it '0', -> this.shouldBeOk()
  it '1', -> this.shouldBeOk()
  it '2', -> this.shouldBeOk()
  it '3', -> this.shouldBeOk()

  it 's.0', -> this.shouldBeOk()
  it 's.1', -> this.shouldBeOk()
  it 's.2', -> this.shouldBeOk()
  it 's.3', -> this.shouldBeOk()
  it 's.4', -> this.shouldBeOk()
  it 's.5', -> this.shouldBeOk()
  it 's.6', -> this.shouldBeOk()
  it 's.7', -> this.shouldBeOk()
  it 's.8', -> this.shouldBeOk()
  it 's.9', -> this.shouldBeOk()
  it 's.10', -> this.shouldBeOk()
  it 's.11', -> this.shouldBeOk()
  it 's.12', -> this.shouldBeOk()
  it 's.13', -> this.shouldBeOk()
  it 's.14', -> this.shouldBeOk()
  it 's.15', -> this.shouldBeOk()
  it 's.16', -> this.shouldBeOk()
  it 's.17', -> this.shouldBeOk()
