['block',
  ['s', ' '],
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['shash', 'a'],
        ['s', ' ']]],
    ['block']],
  ['s', ' '],
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['shash', 'b'],
        ['s', ' ']]],
    ['block']],
  ['s', ' ']]
