['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['s', ' '],
  ['ident', 'x'],
  ['s', ' '],
  ['ident', 'y'],
  ['s', ' '],
  ['block',
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['propertyDelim'],
      ['value',
        ['ident', 'v']]]]]
