['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['s', ' '],
  ['ident', 'x'],
  ['operator', ','],
  ['s', ' '],
  ['ident', 'y'],
  ['s', ' '],
  ['function',
    ['ident', 'x'],
    ['arguments',
      ['number', '1'],
      ['unary', '+'],
      ['number', '2']]],
  ['s', ' '],
  ['block',
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['propertyDelim'],
      ['value',
        ['ident', 'v']]]]]
