['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['commentML', 'test'],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['commentML', 'test'],
      ['propertyDelim'],
      ['commentML', 'test'],
      ['value',
        ['ident', 'v']]],
    ['commentML', 'test']]]
