['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['commentML', 'test'],
  ['ident', 'x'],
  ['commentML', 'test'],
  ['ident', 'y'],
  ['commentML', 'test'],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p'],
        ['commentML', 'test']],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v'],
        ['commentML', 'test']]]]]
