['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['commentML', 'test'],
  ['ident', 'x'],
  ['commentML', 'test'],
  ['operator', ','],
  ['commentML', 'test'],
  ['ident', 'y'],
  ['commentML', 'test'],
  ['funktion',
    ['ident', 'x'],
    ['functionBody',
      ['commentML', 'test'],
      ['number', '1'],
      ['commentML', 'test'],
      ['unary', '+'],
      ['commentML', 'test'],
      ['number', '2'],
      ['commentML', 'test']]],
  ['commentML', 'test'],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p'],
        ['commentML', 'test']],
      ['value',
        ['commentML', 'test'],
        ['ident', 'v'],
        ['commentML', 'test']]]]]
