['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['s', '  '],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['s', '  '],
      ['propertyDelim'],
      ['value',
        ['s', '  '],
        ['ident', 'v'],
        ['s', '  ']]]]]
