['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['s', '  '],
  ['ident', 'x'],
  ['s', '  '],
  ['ident', 'y'],
  ['s', '  '],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p'],
        ['s', '  ']],
      ['propertyDelim'],
      ['value',
        ['s', '  '],
        ['ident', 'v'],
        ['s', '  ']]]]]
