['loop',
  ['atkeyword',
    ['ident', 'while']],
  ['s', ' '],
  ['number', '1'],
  ['s', ' '],
  ['operator', '>'],
  ['s', ' '],
  ['number', '2'],
  ['s', ' '],
  ['block',
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['ident', 'a']]],
      ['block',
        ['declaration',
          ['property',
            ['ident', 'p']],
          ['propertyDelim'],
          ['value',
            ['ident', 'v']]]]]]]

