['loop',
  ['atkeyword',
    ['ident', 'for']],
  ['s', ' '],
  ['variable',
    ['ident', 'i']],
  ['s', ' '],
  ['ident', 'from'],
  ['s', ' '],
  ['number', '1'],
  ['s', ' '],
  ['ident', 'through'],
  ['s', ' '],
  ['number', '3'],
  ['s', ' '],
  ['block',
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['ident', 'a']]],
      ['block',
        ['declaration',
          ['property',
            ['ident', 'p']],
          ['value',
            ['ident', 'v']]]]]]]


