['loop',
  ['atkeyword',
    ['ident', 'each']],
  ['s', ' '],
  ['variable',
    ['ident', 'animal']],
  ['s', ' '],
  ['ident', 'in'],
  ['s', ' '],
  ['ident', 'puma'],
  ['operator', ','],
  ['s', ' '],
  ['ident', 'egret'],
  ['s', ' '],
  ['block',
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['ident', 'a']]],
      ['block',
        ['declaration',
          ['property',
            ['ident', 'p']],
          ['value',
            ['ident', 'v']]]]]]]


