['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['class',
          ['ident', 'nani']]]],
    ['block',
      ['declaration',
        ['property',
          ['ident', 'a']],
        ['propertyDelim'],
        ['value',
          ['ident', 'b']]]]],
  ['decldelim'],
  ['s', ' '],
  ['include',
    ['atkeyword',
      ['ident', 'extend']],
    ['s', ' '],
    ['simpleselector',
      ['class',
        ['ident', 'nani']]]],
  ['decldelim']]