['ruleset',
  ['selector',
    ['simpleselector',
      ['class',
        ['ident', 'test']]]],
  ['block',
    ['filter',
      ['property',
        ['ident', 'filter']],
      ['filterv',
        ['progid',
          ['raw', 'progid:DXImageTransform.Microsoft.AlphaImageLoader(src='images/transparent-border.png',sizingMethod='scale')']]]],
    ['declDelim'],
    ['declaration',
      ['property',
        ['ident', 'color']],
      ['propertyDelim'],
      ['value',
        ['ident', 'red']]]]]
