['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['ident', 's']]],
    ['block',
      ['declaration',
        ['property',
          ['ident', 'p']],
        ['propertyDelim'],
        ['value',
          ['ident', 'v']]]]]]
