['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['class',
          ['ident', 't-1']],
        ['s', ' ']]],
    ['block',
      ['s', '
    '],
      ['declaration',
        ['property',
          ['ident', 'color']],
        ['propertyDelim'],
        ['value',
          ['s', ' '],
          ['ident', 'red']]],
      ['declDelim'],
      ['s', '
']]],
  ['s', '

'],
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['class',
          ['ident', 't-01']],
        ['s', ' ']]],
    ['block',
      ['s', '
    '],
      ['declaration',
        ['property',
          ['ident', 'color']],
        ['propertyDelim'],
        ['value',
          ['s', ' '],
          ['ident', 'blue']]],
      ['declDelim'],
      ['s', '
']]]]
