['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['ident', 'body'],
        ['pseudoc',
          ['function',
            ['ident', 'not'],
            ['functionBody',
              ['simpleselector',
                ['attrib',
                  ['ident', 'x'],
                  ['attrselector', '|'],
                  ['ident', 'x']]]]]],
        ['s', ' ']]],
    ['block']]]
