describe 'css/selector >>', ->

  it '0', -> this.shouldBeOk()
  it '1', -> this.shouldBeOk()
  it '2', -> this.shouldBeOk()
  it '3', -> this.shouldBeOk()
  it '4', -> this.shouldBeOk()
  it '5', -> this.shouldBeOk()
  it '6', -> this.shouldBeOk()
  it '7', -> this.shouldBeOk()
  it '8', -> this.shouldBeOk()
  it '9', -> this.shouldBeOk()
  it '10', -> this.shouldBeOk()
  it '11', -> this.shouldBeOk()
  it '12', -> this.shouldBeOk()
  it '13', -> this.shouldBeOk()
  it '14', -> this.shouldBeOk()
  it '15', -> this.shouldBeOk()
  it '16', -> this.shouldBeOk()
  it '17', -> this.shouldBeOk()
  it '18', -> this.shouldBeOk()
  it '19', -> this.shouldBeOk()
  it '20', -> this.shouldBeOk()

  it 'c.1', -> this.shouldBeOk()
  it 'c.2', -> this.shouldBeOk()
  it 'c.3', -> this.shouldBeOk()
  it 'c.4', -> this.shouldBeOk()

  it 's.0', -> this.shouldBeOk()
  it 's.1', -> this.shouldBeOk()
  it 's.2', -> this.shouldBeOk()
  it 's.3', -> this.shouldBeOk()
  it 's.4', -> this.shouldBeOk()
  it 's.5', -> this.shouldBeOk()
  it 's.6', -> this.shouldBeOk()
