['funktion',
  ['ident', 'test'],
  ['functionBody',
    ['commentML', 'test'],
    ['dimension',
      ['number', '10'],
      ['ident', 'px']],
    ['commentML', 'test'],
    ['operator', ','],
    ['commentML', 'test'],
    ['string', ''test''],
    ['commentML', 'test'],
    ['funktion',
      ['ident', 'test'],
      ['functionBody',
        ['commentML', 'test'],
        ['ident', 'x'],
        ['commentML', 'test']]],
    ['commentML', 'test'],
    ['operator', ','],
    ['commentML', 'test'],
    ['percentage',
      ['number', '89']],
    ['commentML', 'test']]]
