['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's0']],
    ['delim'],
    ['simpleselector',
      ['ident', 's1'],
      ['s', '
']]],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p0']],
      ['propertyDelim'],
      ['value',
        ['ident', 'v0']]],
    ['declDelim'],
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p1']],
      ['propertyDelim'],
      ['value',
        ['ident', 'v1']]]]]
