['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's0']],
    ['delim'],
    ['s', ' '],
    ['commentSL', ' test 1'],
    ['s', '
'],
    ['simpleselector',
      ['ident', 's1'],
      ['s', '
']]],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p1']],
      ['propertyDelim'],
      ['value',
        ['ident', 'v1'],
        ['s', ' '],
        ['commentSL', ' test 2']]],
    ['declDelim'],
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p2']],
      ['propertyDelim'],
      ['value',
        ['ident', 'v2'],
        ['s', ' '],
        ['commentSL', ' test 3']]]]]
