['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's0'],
      ['commentML', 'test']],
    ['delim'],
    ['simpleselector',
      ['commentML', 'test'],
      ['ident', 's1'],
      ['commentML', 'test']]],
  ['block',
    ['commentML', 'test'],
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['commentML', 'test'],
      ['propertyDelim'],
      ['commentML', 'test'],
      ['value',
        ['ident', 'v']]],
    ['commentML', 'test']]]
