['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's'],
      ['s', '  '],
      ['s', '
']]],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p0']],
      ['s', '  '],
      ['propertyDelim'],
      ['s', '  '],
      ['value',
        ['ident', 'v0']]],
    ['s', '  '],
    ['declDelim'],
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p1']],
      ['s', '  '],
      ['propertyDelim'],
      ['s', '  '],
      ['value',
        ['ident', 'v1']]]]]
