['arguments',
  ['function',
    ['ident', 'lighten'],
    ['functionBody',
      ['variable',
        ['ident', 'grey']],
      ['operator', ','],
      ['s', ' '],
      ['percentage',
        ['number', '30']]]],
  ['delim'],
  ['s', ' '],
  ['variable',
    ['ident', 'primary']]]
