['ruleset',
  ['selector',
    ['simpleselector',
      ['ident', 's0']],
    ['delim'],
    ['simpleselector',
      ['ident', 's1']]],
  ['block',
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['propertyDelim'],
      ['value',
        ['ident', 'v']]]]]
