['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['ident', 's0']]],
    ['block',
      ['declaration',
        ['property',
          ['ident', 'p0']],
        ['propertyDelim'],
        ['value',
          ['ident', 'v0']]]]],
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['ident', 's1']]],
    ['block',
      ['declaration',
        ['property',
          ['ident', 'p1']],
        ['propertyDelim'],
        ['value',
          ['ident', 'v1']]]]]]
