['stylesheet',
  ['atruler',
    ['atkeyword',
      ['ident', 'media']],
    ['atrulerq',
      ['s', ' '],
      ['ident', 'test'],
      ['s', ' ']],
    ['atrulers',
      ['s', '
    '],
      ['atruleb',
        ['atkeyword',
          ['ident', 'page']],
        ['s', ' '],
        ['block',
          ['s', '
        '],
          ['declaration',
            ['property',
              ['ident', 'p']],
            ['propertyDelim'],
            ['s', ' '],
            ['value',
              ['ident', 'v']]],
          ['declDelim'],
          ['s', '
    ']]],
      ['s', '
']]]]
