describe 'scss/pseudoc >>', ->

  # CSS
  it '0', -> this.shouldBeOk()
  it '1', -> this.shouldBeOk()
  it '3', -> this.shouldBeOk()
  it '4', -> this.shouldBeOk()
  it '5', -> this.shouldBeOk()
  it '6', -> this.shouldBeOk()
  it '7', -> this.shouldBeOk()
  it '8', -> this.shouldBeOk()
  it '9', -> this.shouldBeOk()
  it '10', -> this.shouldBeOk()
  it '11', -> this.shouldBeOk()
  it '12', -> this.shouldBeOk()
  it '13', -> this.shouldBeOk()
  it '14', -> this.shouldBeOk()
  it '15', -> this.shouldBeOk()
  it '16', -> this.shouldBeOk()

  # SCSS - Interp
  it 'interp.0', -> this.shouldBeOk()
  it 'interp.3', -> this.shouldBeOk()
  it 'interp.4', -> this.shouldBeOk()
  it 'interp.5', -> this.shouldBeOk()
  it 'interp.6', -> this.shouldBeOk()
  it 'interp.7', -> this.shouldBeOk()
  it 'interp.8', -> this.shouldBeOk()
  it 'interp.8.2', -> this.shouldBeOk()
  it 'interp.9', -> this.shouldBeOk()
  it 'interp.9.2', -> this.shouldBeOk()
  it 'interp.15', -> this.shouldBeOk()
  it 'interp.16', -> this.shouldBeOk()
