['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['s', '  '],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['s', '  '],
      ['propertyDelim'],
      ['s', '  '],
      ['value',
        ['ident', 'v']]],
    ['s', '  ']]]
