['atruleb',
  ['atkeyword',
    ['ident', 'test']],
  ['s', '  '],
  ['ident', 'x'],
  ['s', '  '],
  ['operator', ','],
  ['s', '  '],
  ['ident', 'y'],
  ['s', '  '],
  ['function',
    ['ident', 'x'],
    ['arguments',
      ['s', '  '],
      ['number', '1'],
      ['s', '  '],
      ['unary', '+'],
      ['s', '  '],
      ['number', '2'],
      ['s', '  ']]],
  ['s', '  '],
  ['block',
    ['s', '  '],
    ['declaration',
      ['property',
        ['ident', 'p']],
      ['s', '  '],
      ['propertyDelim'],
      ['s', '  '],
      ['value',
        ['ident', 'v']]],
    ['s', '  ']]]
