['atruler',
  ['atkeyword',
    ['ident', 'media']],
  ['atrulerq',
    ['s', ' '],
    ['ident', 'x'],
    ['operator', ','],
    ['s', ' '],
    ['ident', 'y'],
    ['s', ' '],
    ['function',
      ['ident', 'f'],
      ['arguments',
        ['number', '1'],
        ['unary', '+'],
        ['number', '2']]],
    ['s', ' ']],
  ['atrulers',
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['ident', 's']]],
      ['block',
        ['declaration',
          ['property',
            ['ident', 'p']],
          ['propertyDelim'],
          ['value',
            ['ident', 'v']]]]]]]
