['atruler',
  ['atkeyword',
    ['ident', 'media']],
  ['atrulerq',
    ['commentML', 'test'],
    ['ident', 'x'],
    ['commentML', 'test'],
    ['ident', 'y'],
    ['commentML', 'test']],
  ['atrulers',
    ['commentML', 'test'],
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['ident', 's'],
          ['commentML', 'test']]],
      ['block',
        ['commentML', 'test'],
        ['declaration',
          ['property',
            ['ident', 'p'],
            ['commentML', 'test']],
          ['propertyDelim'],
          ['value',
            ['commentML', 'test'],
            ['ident', 'v'],
            ['commentML', 'test']]]]],
    ['commentML', 'test']]]
