['atruler',
  ['atkeyword',
    ['ident', 'media']],
  ['atrulerq',
    ['commentML', 'test'],
    ['ident', 'x'],
    ['commentML', 'test'],
    ['operator', ','],
    ['commentML', 'test'],
    ['ident', 'y'],
    ['commentML', 'test'],
    ['function',
      ['ident', 'f'],
      ['arguments',
        ['commentML', 'test'],
        ['number', '1'],
        ['commentML', 'test'],
        ['unary', '+'],
        ['commentML', 'test'],
        ['number', '2'],
        ['commentML', 'test']]],
    ['commentML', 'test']],
  ['atrulers',
    ['commentML', 'test'],
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['ident', 's'],
          ['commentML', 'test']]],
      ['block',
        ['commentML', 'test'],
        ['declaration',
          ['property',
            ['ident', 'p'],
            ['commentML', 'test']],
          ['propertyDelim'],
          ['value',
            ['commentML', 'test'],
            ['ident', 'v'],
            ['commentML', 'test']]]]],
    ['commentML', 'test']]]
