['atruler',
  ['atkeyword',
    ['ident', '-webkit-keyframes']],
  ['atrulerq',
    ['s', ' '],
    ['ident', 'pulsate'],
    ['s', ' ']],
  ['atrulers',
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['percentage',
            ['number', '0']],
          ['s', ' ']]],
      ['block',
        ['declaration',
          ['property',
            ['ident', 'opacity']],
          ['propertyDelim'],
          ['s', ' '],
          ['value',
            ['number', '.5']]]]],
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['percentage',
            ['number', '50']],
          ['s', ' ']]],
      ['block',
        ['declaration',
          ['property',
            ['ident', 'opacity']],
          ['propertyDelim'],
          ['s', ' '],
          ['value',
            ['number', '1']]]]],
    ['ruleset',
      ['selector',
        ['simpleselector',
          ['percentage',
            ['number', '100']],
          ['s', ' ']]],
      ['block',
        ['declaration',
          ['property',
            ['ident', 'opacity']],
          ['propertyDelim'],
          ['s', ' '],
          ['value',
            ['number', '.5']]]]]]]
