['condition',
  ['ident', 'when'],
  ['s', ' '],
  ['braces', '(', ')',
    ['function',
      ['ident', 'lightness'],
      ['functionBody',
        ['variable',
          ['ident', 'a']]]],
    ['s', ' '],
    ['operator', '>'],
    ['operator', '='],
    ['s', ' '],
    ['percentage',
      ['number', '50']]]]
