['condition',
  ['ident', 'when'],
  ['s', ' '],
  ['braces', '(', ')',
    ['variable',
      ['ident', 'a']],
    ['s', ' '],
    ['operator', '>'],
    ['s', ' '],
    ['number', '10']],
  ['delim'],
  ['s', ' '],
  ['braces', '(', ')',
    ['variable',
      ['ident', 'a']],
    ['s', ' '],
    ['operator', '<'],
    ['s', ' '],
    ['unary', '-'],
    ['number', '10']]]