['condition',
  ['ident', 'when'],
  ['s', ' '],
  ['braces', '(', ')',
    ['funktion',
      ['ident', 'isnumber'],
      ['functionBody',
        ['variable',
          ['ident', 'a']]]]],
  ['s', ' '],
  ['ident', 'and'],
  ['s', ' '],
  ['braces', '(', ')',
    ['variable',
      ['ident', 'a']],
    ['s', ' '],
    ['operator', '>'],
    ['s', ' '],
    ['number', '0']]]