var rules = {
    'arguments': function() { if (s.checkArguments(pos)) return s.getArguments() },
    'atkeyword': function() { if (s.checkAtkeyword(pos)) return s.getAtkeyword() },
    'atruleb': function() { if (s.checkAtruleb(pos)) return s.getAtruleb() },
    'atruler': function() { if (s.checkAtruler(pos)) return s.getAtruler() },
    'atrulerq': function() { if (s.checkAtrulerq(pos)) return s.getAtrulerq() },
    'atrulers': function() { if (s.checkAtrulers(pos)) return s.getAtrulers() },
    'atrules': function() { if (s.checkAtrules(pos)) return s.getAtrules() },
    'attrib': function() { if (s.checkAttrib(pos)) return s.getAttrib() },
    'attrselector': function() { if (s.checkAttrselector(pos)) return s.getAttrselector() },
    'block': function() { if (s.checkBlock(pos)) return s.getBlock() },
    'braces': function() { if (s.checkBraces(pos)) return s.getBraces() },
    'class': function() { if (s.checkClass(pos)) return s.getClass() },
    'combinator': function() { if (s.checkCombinator(pos)) return s.getCombinator() },
    'commentML': function() { if (s.checkCommentML(pos)) return s.getCommentML() },
    'commentSL': function() { if (s.checkCommentSL(pos)) return s.getCommentSL() },
    'condition': function() { if (s.checkCondition(pos)) return s.getCondition() },
    'declaration': function() { if (s.checkDeclaration(pos)) return s.getDeclaration() },
    'declDelim': function() { if (s.checkDeclDelim(pos)) return s.getDeclDelim() },
    'default': function () { if (s.checkDefault(pos)) return s.getDefault() },
    'delim': function() { if (s.checkDelim(pos)) return s.getDelim() },
    'dimension': function() { if (s.checkDimension(pos)) return s.getDimension() },
    'escapedString': function() { if (s.checkEscapedString(pos)) return s.getEscapedString() },
    'filter': function() { if (s.checkFilter(pos)) return s.getFilter() },
    'filterv': function() { if (s.checkFilterv(pos)) return s.getFilterv() },
    'functionExpression': function() { if (s.checkFunctionExpression(pos)) return s.getFunctionExpression() },
    'function': function() { if (s.checkFunction(pos)) return s.getFunction() },
    'ident': function() { if (s.checkIdent(pos)) return s.getIdent() },
    'important': function() { if (s.checkImportant(pos)) return s.getImportant() },
    'include': function () { if (s.checkInclude(pos)) return s.getInclude() },
    'interpolatedVariable': function () { if (s.checkInterpolatedVariable(pos)) return s.getInterpolatedVariable() },
    'interpolation': function () { if (s.checkInterpolation(pos)) return s.getInterpolation() },
    'loop': function() { if (s.checkLoop(pos)) return s.getLoop() },
    'mixin': function () { if (s.checkMixin(pos)) return s.getMixin() },
    'namespace': function() { if (s.checkNamespace(pos)) return s.getNamespace() },
    'nth': function() { if (s.checkNth(pos)) return s.getNth() },
    'nthselector': function() { if (s.checkNthselector(pos)) return s.getNthselector() },
    'number': function() { if (s.checkNumber(pos)) return s.getNumber() },
    'operator': function() { if (s.checkOperator(pos)) return s.getOperator() },
    'parentselector': function () { if (s.checkParentSelector(pos)) return s.getParentSelector() },
    'percentage': function() { if (s.checkPercentage(pos)) return s.getPercentage() },
    'placeholder': function() { if (s.checkPlaceholder(pos)) return s.getPlaceholder() },
    'progid': function() { if (s.checkProgid(pos)) return s.getProgid() },
    'property': function() { if (s.checkProperty(pos)) return s.getProperty() },
    'propertyDelim': function() { if (s.checkPropertyDelim(pos)) return s.getPropertyDelim() },
    'pseudoc': function() { if (s.checkPseudoc(pos)) return s.getPseudoc() },
    'pseudoe': function() { if (s.checkPseudoe(pos)) return s.getPseudoe() },
    'ruleset': function() { if (s.checkRuleset(pos)) return s.getRuleset() },
    's': function() { if (s.checkS(pos)) return s.getS() },
    'selector': function() { if (s.checkSelector(pos)) return s.getSelector() },
    'shash': function() { if (s.checkShash(pos)) return s.getShash() },
    'simpleselector': function() { if (s.checkSimpleSelector(pos)) return s.getSimpleSelector() },
    'string': function() { if (s.checkString(pos)) return s.getString() },
    'stylesheet': function() { if (s.checkStylesheet(pos)) return s.getStylesheet() },
    'unary': function() { if (s.checkUnary(pos)) return s.getUnary() },
    'unknown': function() { if (s.checkUnknown(pos)) return s.getUnknown() },
    'uri': function() { if (s.checkUri(pos)) return s.getUri() },
    'value': function() { if (s.checkValue(pos)) return s.getValue() },
    'variable': function () { if (s.checkVariable(pos)) return s.getVariable() },
    'variableslist': function () { if (s.checkVariablesList(pos)) return s.getVariablesList() },
    'vhash': function() { if (s.checkVhash(pos)) return s.getVhash() }
};

