['conditionalStatement',
  ['condition',
    ['atkeyword',
      ['ident', 'if']],
    ['s', ' '],
    ['number', '1'],
    ['s', ' '],
    ['operator', '>'],
    ['s', ' '],
    ['number', '2']],
  ['s', ' '],
  ['block',
    ['s', ' '],
    ['declaration',
      ['property',
        ['ident', 'color']],
      ['propertyDelim'],
      ['s', ' '],
      ['value',
        ['ident', 'tomato']]],
    ['declDelim'],
    ['s', ' ']]]
