['arguments',
  ['number', '1'],
  ['delim'],
  ['s', ' '],
  ['number', '2'],
  ['delim'],
  ['s', ' '],
  ['number', '3'],
  ['declDelim'],
  ['s', ' '],
  ['ident', 'something'],
  ['delim'],
  ['s', ' '],
  ['ident', 'else']]