['arguments',
  ['declaration',
    ['property',
      ['variable',
        ['ident', 'param1']]],
    ['propertyDelim'],
    ['s', ' '],
    ['value',
      ['ident', 'red'],
      ['operator', ','],
      ['s', ' '],
      ['ident', 'blue']]],
  ['declDelim']]
