['block',
  ['s', '
    '],
  ['declaration',
    ['property',
      ['ident', 'float']],
    ['propertyDelim'],
    ['value',
      ['ident', 'left']]],
  ['declDelim'],
  ['s', '
    '],
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['ident', 'a'],
        ['pseudoc',
          ['ident', 'hover']],
        ['s', ' ']]],
    ['block',
      ['declaration',
        ['property',
          ['ident', 'color']],
        ['propertyDelim'],
        ['value',
          ['ident', 'tomato']]],
      ['declDelim']]],
  ['s', '
']]
