['block',
  ['s', '
    '],
  ['declaration',
    ['property',
      ['ident', 'float']],
    ['propertyDelim'],
    ['value',
      ['ident', 'left']]],
  ['declDelim'],
  ['s', '
    '],
  ['include',
    ['atkeyword',
      ['ident', 'include']],
    ['s', ' '],
    ['simpleselector',
      ['ident', 'nani']],
    ['s', ' '],
    ['block',
      ['declaration',
        ['property',
          ['ident', 'color']],
        ['propertyDelim'],
        ['value',
          ['ident', 'tomato']]],
      ['declDelim']]],
  ['s', '
    ']]
