['simpleselector',
  ['ident', '*'],
  ['namespace'],
  ['ident', '*'],
  ['pseudoc',
    ['function',
      ['ident', 'not'],
      ['arguments',
        ['simpleselector',
          ['ident', '*']]]]]]
