['function',
  ['ident', 'test'],
  ['arguments',
    ['dimension',
      ['number', '10'],
      ['ident', 'px']],
    ['operator', ','],
    ['string', ''test''],
    ['s', ' '],
    ['function',
      ['ident', 'test'],
      ['arguments',
        ['ident', 'x']]],
    ['operator', ','],
    ['percentage',
      ['number', '89']]]]
